import { Box, styled } from '@mui/material';

export const LayoutContainer = styled(Box)({
  '--header-height': '3rem',
  '--font-semi': '600',
  '--first-color': '#ed6958',
  '--text-color': '#0E2431',
  '--text-color-light': '#6c757d',
  '--body-color': '#ffffff',
  '--container-color': '#ffffff',
  '--header-bg': '#ffffff',
  '--nav-link-color': '#0E2431',
  '--nav-link-color-mobile': '#ffffff',
  '--nav-menu-bg': '#0E2431',
  '--shadow-color': 'rgba(14, 36, 49, 0.15)',
  '--shadow-hover': 'rgba(237, 105, 88, 0.3)',
  '--footer-bg': '#0E2431',
  '--footer-text': '#ffffff',
  '--input-bg': '#ffffff',
  '--input-border': '#0E2431',
  '--big-font-size': '2rem',
  '--h2-font-size': '1.25rem',
  '--normal-font-size': '0.938rem',
  '--mb-1': '0.5rem',
  '--mb-2': '1rem',
  '--mb-3': '1.5rem',
  '--mb-4': '2rem',
  '--mb-5': '2.5rem',
  '--mb-6': '3rem',
  '--z-fixed': 100,
  minHeight: '100vh',
  width: '100%',
  backgroundColor: 'var(--body-color)',
  color: 'var(--text-color)',
  transition: 'background-color 0.3s ease, color 0.3s ease',
  '[data-theme="dark"] &': {
    '--first-color': '#ff7a6b',
    '--text-color': '#e0e0e0',
    '--text-color-light': '#a0a0a0',
    '--body-color': '#1a1a2e',
    '--container-color': '#16213e',
    '--header-bg': '#16213e',
    '--nav-link-color': '#e0e0e0',
    '--nav-link-color-mobile': '#e0e0e0',
    '--nav-menu-bg': '#16213e',
    '--shadow-color': 'rgba(0, 0, 0, 0.3)',
    '--shadow-hover': 'rgba(255, 122, 107, 0.4)',
    '--footer-bg': '#0f1419',
    '--footer-text': '#e0e0e0',
    '--input-bg': '#16213e',
    '--input-border': '#e0e0e0',
  },
  '@media screen and (min-width: 768px)': {
    '--big-font-size': '3.5rem',
    '--h2-font-size': '2rem',
    '--normal-font-size': '1rem',
  },
  overflowX: 'hidden',
});
