name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # change if your default branch is different

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.11.0
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npm run build
          cat dist/index.html

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          rm -rf gh-pages-temp
          mkdir gh-pages-temp
          cp -r dist/* gh-pages-temp/
          touch gh-pages-temp/.nojekyll

          cd gh-pages-temp
          git init
          git checkout -b gh-pages

          git add .
          git commit -m "Deploy to gh-pages"

          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin gh-pages --force
